name: Cypress Test
on: 
  push:
    branches:
      - main
jobs:
  Cypress-test-afer-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install all dependencies
        run: |
          npm install
          npm list

      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: chrome
          record: true
          env: |
            CYPRESS_RECORD_KEY : ${{secrets.CYPRESS_RECORD_KEY}}
            CYPRESS_GITHUB_TOKEN : ${{secrets.CYPRESS_GITHUB_TOKEN}}