name: Cypress Test
on: 
  push:
    branches:
      - main
jobs:
  Cypress-test-afer-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install all dependencies
        run: |
          npm install
          npm list

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            # Starts web server for E2E tests - replace with your own server invocation
            # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm start
          record: true

        env:
            # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
            # in GitHub repo → Settings → Secrets → Actions
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
