name: Cypress Test
on: 
 push:
  branches:
  - main
jobs:
  Cypress-test-afer-merge:
   runs-on: ubunto-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
         node-version: 16

    - name: Install all dependencies
      run: |
        npm install
        npm list

    - name: run tests
      run: npm run cypress:open
    
